"""Markdown reporter.

Renders a Problem DNA + ranked claims + experiment plan as a single
human-readable Markdown report.
"""

from __future__ import annotations

from typing import List

from ..schemas import ExperimentPlan, ProblemDNA, RankedClaim


def render_markdown(dna: ProblemDNA, plan: ExperimentPlan, ranked: List[RankedClaim]) -> str:
    lines: list[str] = []
    lines.append(f"# CMRE Report: {dna.title}")
    lines.append("")
    lines.append(f"_Generated by CMRE Engine — competition-agnostic reasoning over {len(ranked)} claims._")
    lines.append("")

    lines.append("## Problem DNA")
    lines.append("")
    lines.append(f"- Platform: `{dna.platform}`")
    lines.append(f"- Task: `{dna.task_type}`")
    lines.append(f"- Modality: `{dna.modality}`")
    lines.append(f"- Metric: `{dna.metric}` ({dna.metric_family})")
    lines.append(f"- Temporal component: `{dna.has_temporal_component}`")
    lines.append(f"- Group structure: `{dna.has_group_structure}`")
    lines.append(f"- Class imbalance: `{dna.class_imbalance}`")
    lines.append(f"- Label noise: `{dna.label_noise_risk}`")
    lines.append(f"- Distribution shift: `{dna.distribution_shift_risk}`")
    lines.append(f"- Leak risks: `{', '.join(dna.leak_risks) or 'none'}`")
    lines.append(f"- Compute constraint: `{dna.compute_constraint}`")
    lines.append(f"- Interpretabilidad: `{dna.interpretability_required}`")
    lines.append("")

    if dna.risk_flags:
        lines.append("### Risk flags")
        for f in dna.risk_flags:
            lines.append(f"- `{f}`")
        lines.append("")

    if dna.validation_recommendations:
        lines.append("### Validation recommendations")
        for r in dna.validation_recommendations:
            lines.append(f"- {r}")
        lines.append("")

    if dna.anti_patterns:
        lines.append("### Anti-patterns to avoid")
        for a in dna.anti_patterns:
            lines.append(f"- {a}")
        lines.append("")

    lines.append("## Ranked techniques")
    lines.append("")
    if not ranked:
        lines.append("_No claims available. Run `cmre seed` or ingest more write-ups._")
        lines.append("")
    else:
        for i, c in enumerate(ranked, start=1):
            lines.append(f"### {i}. Score: `{c.score}`")
            lines.append("")
            lines.append(c.statement)
            lines.append("")
            if c.mechanism_slug:
                lines.append(f"- Mechanism: `{c.mechanism_slug}`")
            if c.technique_slug:
                lines.append(f"- Technique: `{c.technique_slug}`")
            lines.append(f"- Type: `{c.claim_type}`")
            lines.append(f"- Provenance: `{c.provenance_type}`")
            lines.append(f"- Validation: `{c.validation_status}`")
            lines.append(f"- Evidence level: `{c.evidence_level}`")
            lines.append(f"- License: `{c.license_status}`")
            if c.score_breakdown:
                bd = c.score_breakdown
                lines.append(
                    f"- Breakdown: mech={bd.mechanism_fit:.2f} ev={bd.evidence_quality:.2f} "
                    f"constraint={bd.constraint_compatibility:.2f} recency={bd.recency_factor:.2f} "
                    f"modality_bonus={bd.modality_bonus:.2f} "
                    f"prov×={bd.provenance_multiplier:.2f} lic×={bd.license_multiplier:.2f} "
                    f"deterministic={bd.deterministic_score:.2f}"
                )
                if abs(bd.llm_rerank_delta) > 1e-9:
                    lines.append(f"- LLM rerank delta: `{bd.llm_rerank_delta:+.3f}` (bounded ±0.10)")
            if c.reasons:
                lines.append("- Reasons:")
                for r in c.reasons:
                    lines.append(f"  - {r}")
            if c.warnings:
                lines.append("- Warnings:")
                for w in c.warnings:
                    lines.append(f"  - {w}")

            from ..modules.registry import get_module_for_claim

            mod_info = get_module_for_claim(c.mechanism_slug or c.statement)
            if mod_info:
                lines.append(f"- Canonical Module: `{mod_info['module']}` ({mod_info['description']})")

            lines.append("")

    lines.append("## Experiment plan")
    lines.append("")
    for phase in plan.phases:
        lines.append(f"### {phase.name}")
        lines.append("")
        lines.append(f"**Objective:** {phase.objective}")
        lines.append("")
        lines.append("**Actions:**")
        for a in phase.actions:
            lines.append(f"- {a}")
        lines.append("")
        lines.append("**Success criteria:**")
        for s in phase.success_criteria:
            lines.append(f"- {s}")
        if phase.risks:
            lines.append("")
            lines.append("**Risks:**")
            for r in phase.risks:
                lines.append(f"- {r}")
        lines.append("")

    if plan.avoid:
        lines.append("## Avoid")
        lines.append("")
        for a in plan.avoid:
            lines.append(f"- {a}")
        lines.append("")

    if plan.next_steps:
        lines.append("## Next steps")
        lines.append("")
        for s in plan.next_steps:
            lines.append(f"- {s}")
        lines.append("")

    return "\n".join(lines)
